name: prisma

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./playground/.env
    networks:
      - prisma-network
    volumes:
      - prisma-data:/var/lib/postgresql/data

volumes:
  prisma-data:
    driver: local
    name: prisma-data

networks:
  prisma-network:
    driver: bridge
    name: prisma-network
