name: prisma

include:
  - path: ./docker/database/compose.yml

volumes:
  prisma-data:
    driver: local
    name: prisma-data

networks:
  prisma-network:
    driver: bridge
    name: prisma-network
